# Site settings
title: 'ENTSO-E Annual Conference 2015, Brussels'
email: annualconference@entsoe.eu
description: > 
  ENTSO-E's Annual Conference will take place on 20 November 2015 in Brussels.
  Partners for this event are the Florence School of Regulation and the Renewable Grid 
  Initiative. This event is organised under the patronage of the Luxembourg Presidency of the Council.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://conference.entsoe.eu" # the base hostname & protocol for your site
twitter_username: ENTSO_E
locale: en_GB
#github_username:  jekyll

# Build settings
markdown: kramdown

exclude: [entsoe]

collections:
  speakers:
    output: true
    permalink: /speakers/:path/

defaults:
  -
    scope:
      path: 'speakers'
      type: speakers
    values:
      layout: 'speaker'
      category: 'speaker'
      thumb: "https://s3-eu-west-1.amazonaws.com/summitid/people/39294/medium/Bono_copy.jpg?1414688646"
      home_order: 20
#home_order: 13

prose:
  siteurl: "http://conference.entsoe.eu"
  metadata:
    _speakers:
      - name: "name"
        field:
          element: "text"
          label: "Name"
          value: "Speaker Name"
      - name: "wtitle"
        field:
          element: "text"
          label: "Working Title"
          value: "CEO"
      - name: "web"
        field:
          element: "text"
          label: "web link"
          value: "http://"
      - name: "twitter"
        field:
          element: "text"
          label: "Twitter Handle w/o @"
          value: ""
      - name: "thumb"
        field:
          element: "text"
          label: "Picture URL"
          value: "http://"