# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/entsoe_conf" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ENTSO_E
#github_username:  jekyll

# Build settings
markdown: kramdown

exclude: [entsoe]

collections:
  speakers:
    output: true
    permalink: /speakers/:path/

defaults:
  -
    scope:
      path: 'speakers'
      type: speakers
    values:
      layout: 'speaker'
      category: 'speaker'
      thumb: "https://s3-eu-west-1.amazonaws.com/summitid/people/39294/medium/Bono_copy.jpg?1414688646"